-- This file was @generated by Tarmac. It is not intended for manual editing.
return {
	[".icons"] = {
		PowerOff = {
			[".icon"] = "rbxassetid://7361301812",
			[".icon-drop-shadow-dark"] = "rbxassetid://7361301568",
			[".icon-drop-shadow-light"] = "rbxassetid://7361301715",
		},
	},
	Neumorphic = {
		Buttons = {
			Hexagon = {
				["DropShadows-Bevel"] = "rbxassetid://7361302543",
				Fill = "rbxassetid://7361302685",
				Icon = "rbxassetid://7361302802",
				Outline = "rbxassetid://7361302888",
			},
			["Hexagon v2"] = {
				[".drop-shadow-dark"] = "rbxassetid://7361301897",
				[".drop-shadow-light"] = "rbxassetid://7361302004",
				[".shape-fill"] = "rbxassetid://7361302164",
				[".states"] = {
					[".pressed"] = {
						[".inner-shadow-dark"] = "rbxassetid://7361302288",
						[".inner-shadow-light"] = "rbxassetid://7361302401",
					},
				},
			},
		},
	},
}